<?php
foreach($artists as $artist):
    ?>
    <a href="/artist/<?php echo $artist->getMbid() ?>">
    <?php
    echo $artist->getName()."<br>";
    ?>
    </a>
    <img src="<?php echo $artist->getPicture() ?>">
    <br>
    <?php
endforeach;

foreach($songs as $song):
    echo $song->getName()."<br>";
    echo $song->getArtist()."<br>";
    ?>
    <img src="<?php echo $song->getAlbum() ?>">
    <br>
<?php
endforeach;